# Nombre del workflow
name: CI de Node.js

# Cuándo se debe ejecutar
on:
  # Ejecutar en cada push a la rama 'main'
  push:
    branches: ["main"]

# Trabajos que se van a ejecutar
jobs:
  # Nombre del trabajo
  build-and-test:
    # En qué sistema operativo correr
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código del repositorio
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configurar el entorno de Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Instalar dependencias (Paso de "Compilación" para JS)
      - name: Instalar dependencias
        run: npm install

      # 4. Ejecutar las pruebas
      - name: Ejecutar pruebas
        run: npm test
